export const SVG_W = 1200;
  },
  toolbarMeta: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#64748b",
    fontSize: "14px",
    fontWeight: 500,
  },
  canvasWrap: {
    margin: 16,
    overflow: "auto",
    border: "1px solid #e2e8f0",
    borderRadius: "18px",
    background: "#ffffff",
    height: "calc(100vh - 96px)",
  },
  statusBar: {
    gridColumn: "2 / 3",
    gridRow: "2 / 3",
    borderTop: "1px solid #e2e8f0",
    background: "#ffffff",
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
    gap: "16px",
    padding: "0 16px",
    fontSize: "13px",
    color: "#334155",
  },
  statusInfo: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
    overflow: "hidden",
    whiteSpace: "nowrap",
  },
  statusCommand: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  input: {
    minHeight: "32px",
    borderRadius: "10px",
    border: "1px solid #cbd5e1",
    padding: "6px 10px",
    boxSizing: "border-box",
    background: "#ffffff",
  },
  primaryButton: {
    minHeight: "32px",
    borderRadius: "10px",
    border: "1px solid #2563eb",
    background: "#2563eb",
    color: "#ffffff",
    padding: "0 12px",
    cursor: "pointer",
  },
};
